### ISSUE TITLE
gnu apl version 1.8  edif  make fails (ubuntu 18.04)  g++ 7.5

### ISSUE THREAD

**Issue by osmanfb** [ChrisMoller/edif#2]
make  all-recursive
make[1]: Entering directory '/home/carol/edif'
Making all in src
make[2]: Entering directory '/home/carol/edif/src'
git log  -1 --pretty='format:#define GIT_VERSION "%h %ci"' > xxx
echo "" >> xxx
cmp -s xxx gitversion.h; \
rc=$?; \
if [ $rc -eq 0 ]; then rm xxx; else mv xxx gitversion.h; fi
make  all-am
make[3]: Entering directory '/home/carol/edif/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -I/home/carol/apl -I/home/carol/apl/src   -I/usr/local/boost_1_75_0 -MT libedif_la-edif.lo -MD -MP -MF .deps/libedif_la-edif.Tpo -c -o libedif_la-edif.lo `test -f 'edif.cc' || echo './'`edif.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I/home/carol/apl -I/home/carol/apl/src -I/usr/local/boost_1_75_0 -MT libedif_la-edif.lo -MD -MP -MF .deps/libedif_la-edif.Tpo -c edif.cc  -fPIC -DPIC -o .libs/libedif_la-edif.o
edif.cc: In function ‘Token eval_EB(const char*, Value_P, APL_Integer)’:
edif.cc:453:18: error: ‘NC_case_mask’ was not declared in this scope
     switch (nc & NC_case_mask) {
                  ^~~~~~~~~~~~
edif.cc:453:18: note: suggested alternative: ‘__cpu_mask’
     switch (nc & NC_case_mask) {
                  ^~~~~~~~~~~~
                  __cpu_mask
edif.cc:476:17: error: ‘UNI_LF’ was not declared in this scope
      ucs.append(UNI_LF);
                 ^~~~~~
edif.cc:476:17: note: suggested alternative: ‘UNI_EOF’
      ucs.append(UNI_LF);
                 ^~~~~~
                 UNI_EOF
edif.cc:561:19: error: ‘UNI_SPACE’ was not declared in this scope
        ucs.append(UNI_SPACE);
                   ^~~~~~~~~
edif.cc:561:19: note: suggested alternative: ‘TOK_SPACE’
        ucs.append(UNI_SPACE);
                   ^~~~~~~~~
                   TOK_SPACE
edif.cc:569:17: error: ‘UNI_SPACE’ was not declared in this scope
      ucs.append(UNI_SPACE);
                 ^~~~~~~~~
edif.cc:569:17: note: suggested alternative: ‘TOK_SPACE’
      ucs.append(UNI_SPACE);
                 ^~~~~~~~~
                 TOK_SPACE
Makefile:482: recipe for target 'libedif_la-edif.lo' failed
make[3]: *** [libedif_la-edif.lo] Error 1
make[3]: Leaving directory '/home/carol/edif/src'
Makefile:365: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/carol/edif/src'
Makefile:459: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/carol/edif'
Makefile:370: recipe for target 'all' failed
make: *** [all]

am I missing an include file?? I grepped  /usr/include  but could not find any mention of   NC_case_mask

**Comment by osmanfb** [comment]
sorry for the noise. I just  got the latest sources from svn 1497 (apl)  and  and a make clean in the edif directory , now make works.

**Comment by ChrisMoller** [comment]
I was just about to reply that you need a fairly new version of GNU 
APL--I should probably stick a note about that in the README.
